name: openbanking-backend
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.16=h3f729d1_0
  - pip=25.1=pyhc872135_2
  - python=3.11.13=h981015d_0
  - setuptools=78.1.1=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.14=h5e9d12e_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.7.14
      - click==8.2.1
      - colorama==0.4.6
      - fastapi==0.116.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - sniffio==1.3.1
      - starlette==0.47.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
prefix: C:\Users\Enes\anaconda3\envs\openbanking-backend
